### ISSUE TITLE
Quote site - Variable products in a table

### ISSUE THREAD

**Issue by sitehttps** [codersaiful/woo-product-table#348] opened 2024-10-17 03:42 UTC
HI

Using Request A Quote by Addify and your table plugin. When I add a variable product to the table it is add to cart not add to quote
![Test-Variable-Products-1Stop-Shop-Hospitality-Cleaning-10-17-2024_02_41_PM](https://github.com/user-attachments/assets/0d85bd48-087f-43a1-8453-6dce1f0789a1)

**Comment by sarmina5** [comment] 2024-10-22 07:06
Please create a ticket at: https://codeastrology.com/log-in/ 

We need additional information related to your site to check and fix this issue.

**Comment by mdibrahimk48** [comment] 2024-10-23 15:05
The issue is fixed now. 

Need to active Third Party Plugin Support.

**Closed by mdibrahimk48** 2024-10-23 15:05 UTC
