### ISSUE TITLE
"To get all perfect result, Please update your pro version."

### ISSUE THREAD

**Issue by elpistoleroronaldo** [codersaiful/woo-product-table#333] opened 2024-06-07 17:50 UTC
"Minimum Request version: v8.2.4 and your current pro version is: v8.0.0.0"
... and yet when one clicks in 'Get Updates' the link goes to a 404 page.  How does one obtain this vaunted Update for the pro version??

I note that the version of this project is 3.2.5.9 ... so how could I get at least version 8.2.4 of the pro version?  We already have this licen$ed, but getting a pro update seems a bit tough at this point.

**Comment by codersaiful** [comment] 2024-06-07 17:52
If you bought from Codecanyon:
———————————
You can download it from there. To get an auto-update follow this documentation: https://codeastrology.com/get-automatic-updates-from-codecanyon/

**Comment by elpistoleroronaldo** [comment] 2024-06-07 18:15
OK, did all that...  and your plugin now appears on the Envato 'Plugins' page with an install button...

...which fails saying:

Destination folder already exists. /home/srmi/public_html/wp-content/plugins/woo-product-table-pro/

Plugin installation failed.

I would prefer NOT to delete that folder to allow install, because we already have 8 tables set up using that tool.

**Comment by codersaiful** [comment] 2024-06-07 18:16
Deleting the pro plugin won't hamper your created table.

**Comment by elpistoleroronaldo** [comment] 2024-06-07 18:16
you mean the folder or the plugin?

**Comment by codersaiful** [comment] 2024-06-07 18:17
Plugin/folder whatever ........

**Comment by codersaiful** [comment] 2024-06-07 18:17
All tables will keep in free plugin's database

**Comment by mdibrahimk48** [comment] 2024-06-14 11:34
I think the issue is resolved now, so I have closed this ticket. If you have any more questions, please don't hesitate to open a new one.

**Closed by mdibrahimk48** 2024-06-14 11:34 UTC
